# Clippy configuration
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
type-complexity-threshold = 250
trivial-copy-size-limit = 64
pass-by-value-size-limit = 256
